config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "single_pages#index"

  controller :sessions do
    get '/login' => :new
    post '/login' => :create
    delete '/logout' => :destroy
  end
  resources :users, only: [:new, :create]
  get '/dashboard', to: 'users#show'

  resources :items, only: [:index, :show]
  resource :cart, only: [:create, :show, :destroy, :update]
  resources :orders, only: [:index, :show, :create, :update]

  namespace :admin do
    resources :orders, only: [:show]
    resources :items, only: [:new, :create, :edit, :update, :index]
    get '/dashboard', to: 'users#show'
    get '/edit', to: 'users#edit'
    resources :users, only: [:update]
  end

  get '/:slug', to: 'categories#show', as: 'category_items'

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user
  has_many :order_items

  validates_presence_of :original_purchaser, :original_address, :status
  validates_associated :order_items
  before_validation :save_original_purchaser, :save_original_address


  enum status: ['ordered', 'paid', 'cancelled', 'completed']

  def total_cost
    order_items.sum('original_unit_price * quantity')
  end

  def self.by_status(status)
    where(status: status)
  end

  def format_created_time
    created_at.strftime("%m/%d/%Y at %l:%M %p")
  end

  def format_updated_time
    updated_at.strftime("%m/%d/%Y at %i:%M %p")
  end

private

  def save_original_purchaser
    self.original_purchaser ||= user && user.name
  end

  def save_original_address
    self.original_address ||= user && user.address
  end

  def self.retrieve_status(params)
    if params[:status]
      params[:status]
    else
      "All"
    end
  end

  def self.parse_params(params)
  if params[:status]
    where(status: params[:status])
  else
    all
  end
end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :require_admin

  def show
    @order = Order.find(params[:id])
  end

  def index
    @status = params[:status]
    @orders = Order.by_status(@status)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_login

  def show
    if current_user.orders.include?(Order.find(params[:id]))
      @order = current_user.orders.find(params[:id])
    else
      render_404
    end
  end

  def index
    @orders = current_user.orders
  end

  def create
    order = checkout_items
    if order.save
      flash[:success] = "Order was successfully placed"
      redirect_to orders_path
    else
      flash[:danger] = "Unable to create order"
      redirect_to cart_path
    end
  end

  def update
    @orders = Order.update(params[:id], status: params[:status])
    redirect_back(fallback_location: admin_dashboard_path)
  end

private

  def order_params
    params.require(:order).permit(:original_address, :original_purchaser)
  end

  def checkout_items
    order = current_user.orders.new(original_address: current_user.address)
    set_cart.contents.each do |key, value|
      order.order_items.new(
        item_id: key.to_i,
        original_unit_price: Item.find(key.to_i).unit_price,
        original_unit: Item.find(key.to_i).unit,
        quantity: value
      )
    end
    order
  end


end

app/views/admin/orders/_order.html.erb
<li class="order listing list-group-item" >
  <h3> <%= link_to "Order ##{order.id}", admin_order_path(order) %> </h3>
  <% if order.ordered? %>
    <h4 class='cancel-link'><%= link_to "Cancel",  order_path(id: order.id, status: "cancelled"), method: :patch, class: 'btn btn-md btn-danger' %></h4>
    <h4 class='paid-link'><%= link_to "Mark as Paid", order_path(id: order.id, status: "paid"), method: :patch, class: 'btn btn-md btn-info'%></h4>
  <% elsif order.paid? %>
    <h4 class='cancel-link'><%= link_to "Cancel", order_path(id: order.id, status: "cancelled"), method: :patch, class: 'btn btn-md btn-danger' %></h4>
    <h4 class='completed-link'><%= link_to "Mark as Completed", order_path(id: order.id, status: "completed"), method: :patch, class: 'btn btn-md btn-success'%></h4>
  <% end %>
</li>

app/views/admin/orders/show.html.erb
<h1>Order Details</h1>

<div class="breakdown-box">
  <div class="order-breakdown">
    <h3>Purchaser Information</h3>
    <h4>Name: <%= @order.original_purchaser %></h4>
    <h4>Purchaser: <%= @order.original_purchaser %></h4>
    <h4>Adress: <%= @order.original_address %></h4>
    <h4>Order Placed: <%= @order.format_created_time %></h4>
    <h4>Status: <%= @order.status.capitalize %></h4>
    <h4><b>Total Cost: <%= in_dollars(@order.total_cost) %></b></h4>
  </div>
</div>

<ul>
  <h2>Services Ordered</h2>
  <ul class="list-group">
    <%= render @order.order_items %>
  </ul>
</ul>