config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "single_pages#index"

  controller :sessions do
    get '/login' => :new
    post '/login' => :create
    delete '/logout' => :destroy
  end
  resources :users, only: [:new, :create]
  get '/dashboard', to: 'users#show'

  resources :items, only: [:index, :show]
  resource :cart, only: [:create, :show, :destroy, :update]
  resources :orders, only: [:index, :show, :create, :update]

  namespace :admin do
    resources :orders, only: [:show]
    resources :items, only: [:new, :create, :edit, :update, :index]
    get '/dashboard', to: 'users#show'
    get '/edit', to: 'users#edit'
    resources :users, only: [:update]
  end

  get '/:slug', to: 'categories#show', as: 'category_items'

end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || {}
  end

  def total_count
    contents.values.sum
  end

  def add_item(id)
    contents[id.to_s] = (contents[id.to_s] || 0) + 1
  end

  def remove_item(id)
    contents.delete(id.to_s)
    contents
  end

  def count_of(id)
    contents[id.to_s] || 0
  end

  def cart_items
    contents.transform_keys {|key| Item.find(key.to_i)}
  end

  def total_price
    cart_items.sum  {|item, quantity| item.unit_price * quantity}
  end

  def update_quantity(id, new_quantity)
    contents[id.to_s] = new_quantity
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def create
    item = Item.find(params[:item_id])
    @cart.add_item(item.id)
    session[:cart] = @cart.contents
    flash[:success] = "You have successfully added #{item.title} to your cart!"
    redirect_to items_path
  end

  def show
    @items = @cart.cart_items
  end

  def update
    quantity = params[:quantity].to_i
    if quantity.negative?
      flash[:danger] = 'Quantity cannot be negative'
    elsif quantity.zero?
      remove_item
    else
      @cart.update_quantity(params[:item_id], quantity)
      flash[:success] = "Quantity updated"
    end
    redirect_back(fallback_location: cart_path)
  end

  def destroy
    remove_item
    redirect_back(fallback_location: cart_path)
  end

private

  def remove_item
    item = Item.find(params[:item_id])
    @cart.remove_item(item.id)
    session[:cart] = @cart.contents
    flash[:success] = %Q[Successfully removed #{view_context.link_to "#{item.title}", "#{item_path(item)}"} from your cart.]
  end

end

app/views/carts/show.html.erb
<h1> Your Cart </h1>

<div class='cart-items'>
<% if @items.empty? %>
  No services selected yet! Choose a service to get started!
<% else %>
  <ul class="list-group">
    <% @items.each do |item, quantity| %>
    <li class="list-group-item">
      <%= image_tag(item.image_url, size: "100x100", alt: item.title) %>
      <br />
      <h2> Service: <%= link_to "#{item.title}", item_path(item) %> </h2>
      <h3> Description: <%= item.description %> </h3>
      <h4> Unit: <%= item.unit.titleize %> </h4>
      <h4> Unit Price: <%= in_dollars(item.unit_price) %> </h4>
      <%= form_tag(cart_path, method: :put) do %>
        <h4> <%= label_tag("Quantity") %> </h4>
        <%= number_field_tag("quantity", "#{quantity}") %>
        <%= hidden_field_tag :item_id, item.id %>
        <br />
        <br />
        <%= submit_tag("Update Quantity", class: "btn btn-primary") %>
      <% end %>
      <h4> Item Subtotal: <%= in_dollars(item.subtotal(quantity)) %> </h4>
      <%= link_to "Remove Item", cart_path(item_id: item.id), method: :delete, class: "btn btn-danger" %>
      <br />
      <br />
      </li>
    <% end %>
  </ul>

  <h4> Total Before Tax: <%= in_dollars(@cart.total_price) %> </h4><br>
  <% if logged_in? %>
  <%= button_to "Checkout", orders_path(order_created: true), class: "btn btn-success" %>
  <% else %>
  <%= link_to "Login or Create Account to Checkout",  login_path, class: "btn btn-success" %>
  <% end %>
<% end %>
</div>