config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "single_pages#index"

  controller :sessions do
    get '/login' => :new
    post '/login' => :create
    delete '/logout' => :destroy
  end
  resources :users, only: [:new, :create]
  get '/dashboard', to: 'users#show'

  resources :items, only: [:index, :show]
  resource :cart, only: [:create, :show, :destroy, :update]
  resources :orders, only: [:index, :show, :create, :update]

  namespace :admin do
    resources :orders, only: [:show]
    resources :items, only: [:new, :create, :edit, :update, :index]
    get '/dashboard', to: 'users#show'
    get '/edit', to: 'users#edit'
    resources :users, only: [:update]
  end

  get '/:slug', to: 'categories#show', as: 'category_items'

end

app/controllers/single_pages_controller.rb
class SinglePagesController < ApplicationController

  def index
  end
  
end

app/views/single_pages/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Welcome to GigHub!</h1>
  <p class="lead">The is an application that connects users with contractors for various services.</p>

  <% unless logged_in? %>
    <hr class="my-4">
    <p>To get started, either login or create an account below!</p>
    <br />
    <p class="lead">
      <%= link_to 'Create An Account', new_user_path, class: "btn btn-success" %>
      <br />
      <br />
      <%= link_to 'Login', login_path, class: "btn btn-info" %>
    </p>
  <% end %>

</div>