config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "single_pages#index"

  controller :sessions do
    get '/login' => :new
    post '/login' => :create
    delete '/logout' => :destroy
  end
  resources :users, only: [:new, :create]
  get '/dashboard', to: 'users#show'

  resources :items, only: [:index, :show]
  resource :cart, only: [:create, :show, :destroy, :update]
  resources :orders, only: [:index, :show, :create, :update]

  namespace :admin do
    resources :orders, only: [:show]
    resources :items, only: [:new, :create, :edit, :update, :index]
    get '/dashboard', to: 'users#show'
    get '/edit', to: 'users#edit'
    resources :users, only: [:update]
  end

  get '/:slug', to: 'categories#show', as: 'category_items'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CurrentUserHelper

  protect_from_forgery with: :exception
  before_action :set_cart

  def set_cart
    @cart ||= Cart.new(session[:cart])
  end

  def require_login
    redirect_to login_path unless logged_in?
  end

  def require_admin
    render_404 unless admin_logged_in?
  end

  def render_404
    render file: "#{Rails.root}/public/404", layout: false, status: :not_found
  end

  def flash_save_errors(record)
    flash[:danger] = record.errors.full_messages.join("\n")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include CurrentUserHelper

  def in_dollars(cents)
    number_to_currency(cents / 100.0)
  end

end

app/views/application/_flash_message.html.erb
<div class="alert alert-dismissible alert-<%= type %> show" role="alert">
  <p><%= message.html_safe %></p>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/application/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">GigHub</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if admin_logged_in? %>
          <li> <%= link_to "All Services", admin_items_path %> </li>
          <li> <%= link_to "Add New Service", new_admin_item_path %> </li>
        <% else %>
          <li> <%= link_to "All Services", items_path %> </li>
        <% end %>

        <% unless admin_logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Shop By Category <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li><%= link_to category.name, category_items_path(category.slug) %></li>
            <% end %>
          </ul>
        </li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Welcome, <%= current_user.name.titleize %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if admin_logged_in? %>
              <li><%= link_to "Admin Dashboard", dashboard_path %></li>
              <li><%= link_to "Update Admin Info", admin_edit_path %></li>
            <% else %>
              <li><%= link_to "My Dashboard", dashboard_path %></li>
              <li><%= link_to "My Orders", orders_path %></li>
            <% end %>
          </ul>
        </li>
        <% end %>

        <li>
        <%= link_to cart_path, id: 'go-to-cart', type: "button", class: "btn btn-lg" do %>
          <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true">
          </span>
        <% end %>
        </li>

        <% if logged_in? %>
          <li><%= link_to 'Logout', logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>